# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRzqYfLdarN9hzziOYuWhaF9m9tbEIPu

**Install Dependencies**
"""

"""**Import dependencies**"""

import os
import pandas as pd
import yfinance as yf
import alpaca as tradeapi
import alpaca_trade_api as tradeapi
import configparser
import pytz
import locale
import pandas_market_calendars as mcal

from alpaca_trade_api.rest import REST, TimeFrame, APIError
import alpaca_trade_api as alpaca
from ta.volatility import BollingerBands
from ta.momentum import RSIIndicator
from ta.trend import sma_indicator
from tqdm import tqdm
from requests_html import HTMLSession
from datetime import datetime
from slack import WebClient
from slack.errors import SlackApiError
import time
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame
from alpaca.trading.client import TradingClient
from alpaca.trading.requests import MarketOrderRequest
from alpaca.trading.enums import OrderSide, TimeInForce
from datetime import datetime
from dateutil.relativedelta import relativedelta
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense, Dropout, LSTM
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error
import json
import logging
#import config
import asyncio
from lumibot.brokers import Alpaca
from lumibot.backtesting import YahooDataBacktesting
from lumibot.strategies.strategy import Strategy
from lumibot.traders import Trader
from datetime import datetime
from alpaca_trade_api import REST
#from timedelta import Timedelta
time.sleep(1)
from google.colab import drive
drive.mount('/content/drive')


"""**Crypto Machine Learning: Develop a Crypto Algorithmic Trading Strategy**

The Application machine learning techniques to develop, test, and implement algorithmic trading strategies in the cryptocurrency space.
More specifically, utilizing the unsupervised machine learning algorithm called the **Hierarchical Risk Parity (HRP) portfolio strategy**.

**Configure API Keys**
For accessing crypto data and automating trades, we will be using the CoinGecko and Alpaca APIs.

CoinGecko API: Used to fetch cryptocurrency market data.
Alpaca API: Enables automated trading on the Alpaca platform.
"""

from google.colab import userdata
coingecko_key = userdata.get('CoinGeckoAPIKEY')
alpaca_key = userdata.get('ALPACA_PAPER_TRADING_KEY')
alpaca_secret = userdata.get('ALPACA_PAPER_TRADING_SECRET')

## Install Required Libraries
# pycgapi: A client for accessing the CoinGecko API for cryptocurrency data.
# alpaca-py: The official Python library for the Alpaca trading API, enabling
# automated trading strategies.
# PyPortfolioOpt: Offers portfolio optimization techniques, such as mean-variance
# optimization.
# bt: A flexible backtesting framework for Python used to test and develop
# quantitative trading strategies.

#%%capture

## Import Libraries

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import math
import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from tqdm import tqdm
from datetime import datetime, timedelta
from typing import Any, Tuple

from sklearn.preprocessing import StandardScaler
from scipy.cluster.hierarchy import dendrogram, linkage
from scipy.stats import norm, t, ttest_1samp

from pycgapi import CoinGeckoAPI
from alpaca.trading.client import TradingClient
from alpaca.trading.requests import GetAssetsRequest, MarketOrderRequest
from alpaca.trading.enums import AssetClass, OrderSide, TimeInForce

from pypfopt.risk_models import CovarianceShrinkage
from pypfopt.hierarchical_portfolio import HRPOpt
from pypfopt.expected_returns import returns_from_prices

import bt
import ffn
import time
from requests.exceptions import RetryError

"""**Initialize API Clients, Get tradable crypto assets on Alpaca, Crypto Tickers from CoinGecko, Collect CoinGecko Coin IDs, and Map CoinGecko Coin IDs to Alpaca Trading Symbols**"""

## Initialize API Clients

# Now, let's set up the clients needed to interact with the CoinGecko and
# Alpaca APIs. These clients act as the bridge between our Python code and the
# external services, allowing us to fetch real-time cryptocurrency data and
# execute trades programmatically.

# Configuration Variables
pro_api = False  # Set to True if using a paid CoinGecko API key
paper = True  # Set to False for live trading on Alpaca

# Initialize the CoinGecko API client
cg = CoinGeckoAPI(coingecko_key, pro_api=pro_api)
# Check API server status
try:
    status = cg.status_check()
    print("CoinGecko API Server Status:", status)
except Exception as e:
    print("Error checking CoinGecko API status:", e)

# Initialize the Alpaca trading client
trading_client = TradingClient(alpaca_key, alpaca_secret, paper=paper)
# Output initialization status
trading_mode = "Paper Trading" if paper else "Live Trading"
print(f"Alpaca Trading Client Initialized: {trading_mode}")

# Tradable Crypto Tickers on Alpaca
# First, we retrieve all tradable cryptocurrency tickers from Alpaca,
# focusing on those we can trade and have data for on CoinGecko.

# Get tradable crypto assets on Alpaca
search_params = GetAssetsRequest(asset_class=AssetClass.CRYPTO)
assets = trading_client.get_all_assets(search_params)
tradable_assets = pd.DataFrame([
    {'symbol': asset.symbol, 'tradable': asset.tradable}
    for asset in assets
]).set_index('symbol').sort_index()
print('Tradable Currency Pairs on Alpaca:\n')
print(tradable_assets.to_markdown())

## Crypto Tickers from CoinGecko
# Next, we match the tradable tickers from Alpaca with CoinGecko coin IDs,
# excluding those with a base currency of "BTC" to focus on US Dollar-based pairs.

# Store CoinGecko search results for tickers
search_results_dict = {}
'''for symbol in tqdm(tradable_assets.index):
    quote_currency, base_currency = symbol.split('/')
    if base_currency == 'USD' and tradable_assets.loc[symbol, 'tradable']:
        search_results = cg.search_coingecko(query=quote_currency)['coins']
        search_results_dict[symbol] = search_results'''

for symbol in tqdm(tradable_assets.index):
    quote_currency, base_currency = symbol.split('/')
    if base_currency == 'USD' and tradable_assets.loc[symbol, 'tradable']:
        retries = 3
        while retries > 0:
            try:
                search_results = cg.search_coingecko(query=quote_currency)['coins']
                search_results_dict[symbol] = search_results
                time.sleep(1)  # Rate-limiting delay
                break  # Exit the retry loop on success
            except RetryError as e:
                retries -= 1
                if retries == 0:
                    print(f"Failed to fetch {symbol} after retries.")
                else:
                    time.sleep(5)  # Backoff before retrying
# Display search results
print(f"\n\nFound CoinGecko IDs for {len(search_results_dict)} assets.")

## Collect CoinGecko Coin IDs

# We collect the CoinGecko coin IDs from the search results,
# excluding stablecoins to focus on risky assets.

# Dictionary for storing found CoinGecko coin IDs
found_coin_ids = {
    key: value['id'].iloc[0] for key, value in search_results_dict.items()
}
# Sorting coin IDs
coin_ids = sorted(found_coin_ids.values())
# Define a list of stablecoins to exclude
stablecoins = ['tether', 'usd-coin']
# Filtering out stablecoins to focus on risky assets
risky_assets = [
    coin_id for coin_id in coin_ids if coin_id not in stablecoins
]
# Displaying CoinGecko Coin IDs
print('CoinGecko Coin IDs: \n')
for coin_id in risky_assets:  # Changed to risky_assets for relevant output
    print(coin_id)

## Map CoinGecko Coin IDs to Alpaca Trading Symbols

# Finally, we create a mapping between the CoinGecko coin IDs and Alpaca
# trading symbols for use in subsequent trading logic.

# Create a dictionary mapping CoinGecko coin IDs to Alpaca trading symbols
ticker_mapping = {value: key.upper() for key, value in found_coin_ids.items()}
# Display ticker mapping
print("Ticker Mapping:\n")
for key, value in ticker_mapping.items():
    print(f"{key}: {value}")

"""**Fetching Real-time & Historical Crypto Price Data**

**Get Earliest Start Dates, Current Prices, Historical Data, Categorical Data, Perform Data Processing, and Prepare Data for Machine Learning**
"""

# Use the CoinGecko API to fetch real-time and historical crypto price data.
# This is essential for the analysis underlying our trading strategy.

## Earliest Start Dates

# The availability of historical data is assessed to ensure each cryptocurrency
# in our selection has sufficient historical data for analysis.
# Use this information to assess whether you should to omit any assets whose
# earliest start date is too recent.

# Store each coin's earliest start date available
dfs = {}
for coin_id in tqdm(risky_assets):
    #historical_data = cg.coin_historical_market_data(coin_id)
    historical_data = cg.coin_historical_market_data(coin_id, days=365)
    first_date = historical_data.index[0].strftime('%Y-%m-%d')
    dfs[coin_id] = first_date
# Create dataframe of earliest start dates
start_dates = pd.DataFrame.from_dict(
    dfs, orient='index', columns=['Start Dates']
)
# Display earliest start dates
print(
    "\n\nEarliest Data Start Dates:\n\n",
    start_dates.squeeze().sort_values(ascending=False)
)

## Current Prices
# We download current market prices for each selected cryptocurrency, providing
# a current view of market conditions.

# Get current prices for each coin
current_prices = cg.simple_prices(coin_ids)
# Mapping CoinGecko IDs to their corresponding Alpaca symbols
current_prices.index = current_prices.index.map(ticker_mapping)
# Display current prices
print("Current Prices:\n\n", current_prices)

## Historical Data
# We download historical price, market capitalization, and trading volume data
# for each selected cryptocurrency.

# Get historical price, market cap, and volume for each coin
# Calculate today's date and subtract one day
to_date = (datetime.now() - timedelta(days=1)).strftime('%d-%m-%Y')
# Adjust the code to use the calculated to_date
historical_data = cg.multiple_coins_historical_data(
    coin_ids, from_date='01-09-2024', to_date=to_date
)
# Create a copy of the historical data
historical_prices = historical_data['price'].copy()
historical_market_cap = historical_data['market_cap'].copy()
historical_volume = historical_data['total_volume'].copy()
# Display historical prices for selected columns
print('\n\nHistorical Prices:\n')
print(historical_prices.head().iloc[:, 3:8])

## Categorical Data

# Finally, categorical information for each cryptocurrency is collected.
# This data helps to understand the diversification and exposure of the portfolio
# across different cryptocurrency categories.

# Download and store categorical data for each coin
categories_dict = {}
for coin_id in tqdm(coin_ids):
    categories_dict[coin_id] = cg.coin_info(coin_id)['categories']

## Data Processing

# This section outlines the steps to normalize, analyze, and visualize the
# historical cryptocurrency data, setting a foundation for machine learning
# analysis.

# Normalize Prices for Comparative Analysis
# Given the significant price differences across cryptocurrencies, we normalize
# all prices to start at $1. This approach enables a direct comparison by
# equalizing the initial investment across all assets.

# Normalize prices to start at $1 for comparative analysis
historical_prices = historical_prices.rebase(1)

# Compute Historical Returns
# We calculate daily and cumulative returns from the normalized prices,
# which serve as key metrics for evaluating asset performance.

# Calculate daily returns
historical_returns = historical_prices.pct_change().dropna()
historical_returns.index = historical_returns.index
# Calculate cumulative returns from daily returns
cumulative_returns = (1 + historical_returns).cumprod() - 1

# Visualize Cumulative Returns
# Visualizing the cumulative returns of selected cryptocurrencies not only brings
# the data to life but also aids in the identification of standout performers
# and underperformers within our investment universe.

plt.figure(figsize=(10, 6))
# Plot cumulative returns for each cryptocurrency
for column in cumulative_returns.columns:
    plt.plot(cumulative_returns.index, cumulative_returns[column], label=column)
# Configure the x-axis to show dates correctly
plt.gca().xaxis.set_major_locator(mdates.MonthLocator(interval=3))
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
plt.gcf().autofmt_xdate()  # Auto-format date labels
plt.title('Cumulative Returns Over Time', fontsize=16)
plt.xlabel('Date', fontsize=14)
plt.ylabel('Cumulative Returns', fontsize=14)
plt.legend(title='Cryptocurrency', loc='center left', bbox_to_anchor=(1, 0.5))
plt.grid(True, which='major', axis='both')  # Show major grid lines only
plt.tight_layout()
plt.show()

## Prepare Data for Machine Learning

# Prior to machine learning analysis, we standardize the historical returns.
# This normalization ensures that all data features contribute equally to the
# analysis, improving algorithm performance.

# Standardize historical returns
scale = StandardScaler()
historical_returns_scaled = pd.DataFrame(
    scale.fit_transform(historical_returns),
    columns=historical_returns.columns,
    index=historical_returns.index
).clip(lower=-3, upper=3)
print('Standardized Historical Returns:\n')
print(historical_returns_scaled.iloc[:, 3:8].head())

"""**Algorithmic Trading Strategy: What is Hierarchical Risk Parity (HRP)?**

The Hierarchical Risk Parity (HRP) method uses hierachical clustering to group assets, not by past returns, but by the similarity in their price series.

HRP aims to minimize estimation errors found in conventional portfolio optimization methods by constructing a diversified portfolio that considers the hierarchical relationships between assets.

**Perform Hierarchical Risk Parity, Portfolio Optimization, Categorical Weighting, Backtesting Strategy (Hierarchical Risk Parity (HRP), Equal Risk Contribution (ERC) Strategy, Equal_Weighted Strategy, & Randomly_Weighted Strategy), Run the Backtest, Plot Security Weights, and **
"""

## Hierarchical Risk Parity

# We start by structuring our assets using hierarchical clustering. This method
# begins with each asset as a separate cluster and merges them iteratively based
# on their correlations. The outcome reveals natural groupings in the data,
# aiding in diversified portfolio construction.

# Prepare data for clustering
scaled_data = historical_returns_scaled.loc[:, risky_assets]
# Hierarchical clustering
linkage_matrix = linkage(scaled_data.T, method='ward')
# Dendrogram plot
plt.figure(figsize=(10, 6))
dendrogram(linkage_matrix, labels=scaled_data.columns, leaf_rotation=90)
plt.title('Asset Clusters by Hierarchical Clustering')
plt.xlabel('Cryptocurrency')
plt.ylabel('Distance')
plt.show()

## Portfolio Optimization

# In the portfolio optimization phase, Hierarchical Risk Parity (HRP) is employed
# to integrate the clustering results into the asset allocation process.

# Calculate the covariance matrix using the Ledoit-Wolf shrinkage method
covariance_matrix = CovarianceShrinkage(
    historical_returns[risky_assets].loc[
        historical_returns.index[-1] - pd.DateOffset(months=3):]
).ledoit_wolf()
# Optimize the portfolio with the HRP model
hrp = HRPOpt(historical_returns[risky_assets], covariance_matrix)
hrp_portfolio = hrp.optimize(linkage_method='ward')
weights = hrp.clean_weights()
# Convert the optimized weights into a readable DataFrame
weights = pd.DataFrame(
    list(weights.items()),
    columns=['Asset', 'Optimized Weights']
).sort_values(by='Optimized Weights', ascending=False)
weights.set_index('Asset', inplace=True)
# Format and print the optimized weights
weights_formatted = weights.copy()
weights_formatted['Optimized Weights'] = (
    weights_formatted['Optimized Weights'] * 100
).round(2).astype(str) + '%'
print('HRP Optimized Portfolio:\n')
print(weights_formatted)
print('\n')
performance = hrp.portfolio_performance(verbose=True)

# The performance metrics, which include expected annual return, annual volatility,
# and Sharpe Ratio, provide a comprehensive view of the portfolio's risk-reward profile.

## Categorical Weighting

# Finally, we use categorical data to evaluate our portfolio's exposure across
# various cryptocurrency categories.
# Sum weights for each category across all assets
category_weights = {}
for asset, weight in weights['Optimized Weights'].items():
    for category in categories_dict.get(asset, []):
        category_weights[category] = category_weights.get(category, 0) + weight
# Format the aggregated weights as a percentage series
category_weights = pd.Series(category_weights) * 100
# Define the categories of interest
categories_of_interest = [
    'Layer 0 (L0)', 'Layer 1 (L1)', 'Proof of Work (PoW)',
    'Proof of Stake (PoS)', 'Governance', 'Smart Contract Platform',
    'Decentralized Finance (DeFi)', 'Meme'
]
# Filter to only include the categories of interest and sort
category_weights = category_weights.filter(items=categories_of_interest)
category_weights = category_weights.sort_values(ascending=False)
# Name the Series and format as percentages
category_weights.name = 'Category Weights'
category_weights = category_weights.apply("{:.2f}%".format)
# Display categorical weightings in descending order
print('Categorical Weights:\n')
print(category_weights)
print('\nNote: Categories can overlap so weights unlikely to total 100%.')

## Backtesting Strategy
# Backtesting is a crucial step in evaluating the performance of any trading
# strategy. It allows us to simulate how the strategy would have performed in the
# past, providing insights into potential future performance.

# Backtesting Hierarchical Risk Parity (HRP) Strategy
# The HRP strategy aims to optimize asset allocation by considering the
# hierarchical structure of asset correlations, thus potentially reducing
# portfolio volatility and improving returns.

class WeighHRP(bt.Algo):
    def __init__(self, prices, assets, lookback):
        self.prices = prices
        self.assets = assets
        self.lookback = lookback
    def __call__(self, target):
        end_date = target.now
        # Calculate start_date as lookback months before end_date
        start_date = end_date - pd.DateOffset(months=self.lookback)
        # Adjust start_date to the closest available date in prices
        available_start_dates = self.prices.index[
            self.prices.index >= start_date]
        if not available_start_dates.empty:
            adjusted_start_date = available_start_dates[0]
        else:
            print("No available start date found after the "
                  "calculated start date.")
            return False
        # Adjust end_date to the closest available date in prices
        available_end_dates = self.prices.index[
            self.prices.index <= end_date]
        if not available_end_dates.empty:
            adjusted_end_date = available_end_dates[-1]
        else:
            print("No available end date found before the calculated end date.")
            return False
        # Extract period_prices using adjusted start and end dates
        period_prices = self.prices[self.assets].loc[
            adjusted_start_date:adjusted_end_date]
        # Check if there's sufficient data within this adjusted period
        if len(period_prices) > 1:
            period_returns = returns_from_prices(period_prices)
            covariance_matrix = CovarianceShrinkage(period_prices).ledoit_wolf()
            hrp = HRPOpt(period_returns, covariance_matrix)
            hrp_portfolio = hrp.optimize(linkage_method='ward')
            target.temp['weights'] = hrp.clean_weights()
            return True
        else:
            return False

# Backtesting Equal Risk Contribution (ERC) Strategy
# The ERC strategy seeks to allocate portfolio weights in a way that each asset
# contributes equally to the portfolio's risk, aiming for a more balanced risk
# distribution across assets.

class WeighERC(bt.Algo):
    def __init__(self, prices, assets, lookback=3,
                 initial_weights=None, risk_weights=None,
                 covar_method="ledoit-wolf", risk_parity_method="ccd",
                 maximum_iterations=100, tolerance=1e-8):
        self.prices = prices
        self.assets = assets
        self.lookback = pd.DateOffset(months=lookback)
        self.initial_weights = initial_weights
        self.risk_weights = risk_weights
        self.covar_method = covar_method
        self.risk_parity_method = risk_parity_method
        self.maximum_iterations = maximum_iterations
        self.tolerance = tolerance
    def __call__(self, target):
        end_date = target.now
        # Calculate start_date as 'lookback' period before end_date
        start_date = end_date - self.lookback
        # Adjust start_date to the closest available date in prices
        available_start_dates = self.prices.index[
            self.prices.index >= start_date]
        if not available_start_dates.empty:
            adjusted_start_date = available_start_dates[0]
        else:
            print("No available start date found after the "
                  "calculated start date.")
            return False
        # Adjust end_date to the closest available date in prices
        available_end_dates = self.prices.index[
            self.prices.index <= end_date]
        if not available_end_dates.empty:
            adjusted_end_date = available_end_dates[-1]
        else:
            print("No available end date found before the "
                  "calculated end date.")
            return False
        # Extract period_prices using adjusted start and end dates
        period_prices = self.prices[self.assets].loc[
            adjusted_start_date:adjusted_end_date]
        # Ensure there's sufficient data to proceed with ERC weight calculation
        if len(period_prices) > 1:
            # Calculate returns and proceed with ERC calculation
            period_returns = period_prices.pct_change().dropna()
            try:
                tw = bt.ffn.calc_erc_weights(
                    period_returns,
                    initial_weights=self.initial_weights,
                    risk_weights=self.risk_weights,
                    covar_method=self.covar_method,
                    risk_parity_method=self.risk_parity_method,
                    maximum_iterations=self.maximum_iterations,
                    tolerance=self.tolerance,
                )
                target.temp['weights'] = tw
                return True
            except Exception as e:
                print(f"Error calculating ERC weights: {e}")
                return False
        else:
            return False

# Backtesting Equal Weighted (EW)

# Backtesting Randomly Weighted (RW)

# Backtest Engine
# The backtest engine simulates the performance of these strategies over a
# specified period. It uses historical price data to execute trades according to
# each strategy's logic and calculates the portfolio's value over time.

def run_backtest(prices: pd.DataFrame, assets: list, market_caps: pd.DataFrame,
                 risk_free_rate: float = 0.0, nsim: int = 100,
                 lookback: int = 3):
    """Run all backtests and plot results.
    Args:
        prices: Historical prices for the selected assets.
        assets: List of asset symbols.
        market_caps: Historical market cap.
        risk_free_rate: Risk-free rate. Defaults to 0.0.
        nsim: Number of simulations for random benchmark. Defaults to 100.
        lookback: Lookback period in months for historical data. Defaults to 3.
    Returns:
        tuple: A tuple containing the backtest results for each strategy.
    """
    # Adjustments for earliest start date remain the same
    earliest_start_date = prices.index.min() + pd.DateOffset(months=3)
    filtered_prices = prices.loc[earliest_start_date:].ffill()
    # Define strategies
    hrp_strategy = bt.Strategy('Hierachical_Risk_Parity',
                              [bt.algos.RunMonthly(),
                              bt.algos.SelectAll(),
                              WeighHRP(prices, assets, lookback),
                              bt.algos.Rebalance()])
    ew_strategy = bt.Strategy('Equal_Weighted',
                             [bt.algos.RunMonthly(),
                             bt.algos.SelectAll(),
                             bt.algos.WeighEqually(),
                             bt.algos.Rebalance()])
    erc_strategy = bt.Strategy('Equal_Risk_Contribution',
                              [bt.algos.RunMonthly(),
                              bt.algos.SelectAll(),
                              WeighERC(prices, assets),
                              bt.algos.Rebalance()])
    random_strategy = bt.Strategy('Randomly_Weighted',
                                 [bt.algos.RunMonthly(),
                                 bt.algos.SelectRandomly(),
                                 bt.algos.WeighRandomly(),
                                 bt.algos.Rebalance()])
    # Create backtests
    hrp_backtest = bt.Backtest(hrp_strategy, filtered_prices[assets])
    ew_backtest = bt.Backtest(ew_strategy, filtered_prices[assets])
    erc_backtest = bt.Backtest(erc_strategy, filtered_prices[assets])
    # Run backtests
    total_result = bt.run(
        hrp_backtest,
        ew_backtest,
        erc_backtest
    )
    hrp_result = bt.run(hrp_backtest)
    ew_result = bt.run(ew_backtest)
    erc_result = bt.run(erc_backtest)
    # Run monte carlo simulation of many random portfolios
    random_benchmark_results = bt.backtest.benchmark_random(
        hrp_backtest,
        random_strategy,
        nsim
    )
    # Set the risk-free rate
    total_result.set_riskfree_rate(risk_free_rate)
    hrp_result.set_riskfree_rate(risk_free_rate)
    ew_result.set_riskfree_rate(risk_free_rate)
    erc_result.set_riskfree_rate(risk_free_rate)
    random_benchmark_results.set_riskfree_rate(risk_free_rate)
    # Plot results
    total_result.plot(figsize=(10, 6))
    plt.title('Backtest Results')
    plt.xlabel('Date')
    plt.ylabel('Portfolio Value')
    plt.legend(title='Strategy', bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True)
    plt.show()
    return (
        total_result, hrp_result, ew_result, erc_result,
        random_benchmark_results
    )

# Run the Backtest
# To initiate the backtest, we set the number of simulations for random portfolios
# and the lookback period for rebalancing.

nsim = 1000  # number of random portfolios to be simulated
lookback = 3  # period in months used to recalculate weights

# The risk-free rate is also defined to calculate the excess return used for
# risk-adjusted performance.

# Get start and end dates
start_date = historical_prices.index.min()
end_date = historical_prices.index.max()
# Get historical risk-free rate
risk_free_rate = round(bt.get(
    '^TNX',
    start=start_date,
    end=end_date
).mean().values[0]/100, 4)
print('Average Risk-Free Rate: {}%'.format(risk_free_rate*100))

# Run all backtests and plot the performance results of a $100 starting value
# portfolio for each backtest.

# Run our backtests
total_result, hrp_result, ew_result, erc_result, random_benchmark_results = \
    run_backtest(
        historical_prices,
        risky_assets,
        historical_market_cap,
        risk_free_rate=risk_free_rate,
        nsim=nsim,
        lookback=lookback
    )

# Plot Security Weights
# Visualizing the weight allocations over time provides insights into how each
# strategy changes to market conditions. It helps in understanding the
# diversification and risk management approach of each strategy.

def plot_security_weights(result, name):
    result.get_security_weights().plot(figsize=(10, 6))
    plt.title(f'{name} Portfolio Weights')
    plt.xlabel('Date')
    plt.ylabel('Weight')
    plt.legend(title='Asset', bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid()
    plt.show()

plot_security_weights(hrp_result, name='HRP')  # Hierarchical Risk Parity (HRC)
plot_security_weights(ew_result, name='EW')  # Equal Weight
plot_security_weights(erc_result, name='ERC')  # Equal Risk Contribution (ERC)

"""**Display Backtest Results**

After running the backtests, we compile and display the performance statistics for each strategy. This includes measures such as total return, annualized return, maximum drawdown, Sharpe ratio, and others. Comparing these metrics across strategies helps in evaluating their relative performance and risk characteristics.
"""

# Compile strategy and benchmark statistics
strategy_performance_stats = pd.concat([
    total_result.stats.iloc[:2],
    total_result.stats.iloc[2:].astype(float)
]).squeeze()

# Compute the Aggregate Random Portfolio statistics
random_performance_stats = pd.concat([
    random_benchmark_results.stats.iloc[:2, 1],
    random_benchmark_results.stats.iloc[2:, 1:].astype(float).mean(axis=1)
])
random_performance_stats.name = 'Aggregate_Random_Portfolio'

# Concatenate the strategy and random portfolio statistics
total_performance_stats = pd.concat([
    strategy_performance_stats,
    random_performance_stats
], axis=1).dropna()

# Function to format as percentage or plain number based on the field type
def format_value(val, as_percentage=False):
    if isinstance(val, pd.Timestamp):
        return val.strftime('%Y-%m-%d')
    try:
        numeric_val = pd.to_numeric(val)
        if pd.isnull(numeric_val):
            return "-"
        return f"{numeric_val * 100:.2f}%" if as_percentage else f"{numeric_val:.2f}"
    except ValueError:
        # Return the value as is if it's not numeric
        return val

# Define the fields that should be formatted as percentages
percentage_fields = [
    'rf', 'total_return', 'cagr', 'max_drawdown', 'mtd', 'three_month',
    'six_month', 'ytd', 'one_year', 'incep', 'daily_mean', 'best_day',
    'worst_day', 'monthly_mean', 'best_month', 'worst_month', 'yearly_mean',
    'best_year', 'worst_year', 'avg_drawdown', 'daily_vol', 'monthly_vol',
    'avg_up_month', 'avg_down_month', 'win_year_perc', 'twelve_month_win_perc'
]

# Copy for formatting
display_performance_stats = total_performance_stats.copy()

# Apply formatting only to numeric fields
for field in display_performance_stats.index:
    if field not in ['Start', 'End']:  # Exclude date fields from numeric formatting
        is_percentage = field in percentage_fields
        display_performance_stats.loc[field] = display_performance_stats.loc[
            field].apply(format_value, as_percentage=is_percentage)

# Rename the indices for display
rename_dict = {
    'start': 'Start',
    'end': 'End',
    'rf': 'Risk-free rate',
    'total_return': 'Total Return',
    'cagr': 'CAGR',
    'max_drawdown': 'Max Drawdown',
    'calmar': 'Calmar Ratio',
    'mtd': 'MTD',
    'three_month': '3m',
    'six_month': '6m',
    'ytd': 'YTD',
    'one_year': '1Y',
    'incep': 'Since Incep. (ann.)',
    'daily_sharpe': 'Daily Sharpe',
    'daily_sortino': 'Daily Sortino',
    'daily_mean': 'Daily Mean (ann.)',
    'daily_vol': 'Daily Vol (ann.)',
    'daily_skew': 'Daily Skew',
    'daily_kurt': 'Daily Kurt',
    'best_day': 'Best Day',
    'worst_day': 'Worst Day',
    'monthly_sharpe': 'Monthly Sharpe',
    'monthly_sortino': 'Monthly Sortino',
    'monthly_mean': 'Monthly Mean (ann.)',
    'monthly_vol': 'Monthly Vol (ann.)',
    'monthly_skew': 'Monthly Skew',
    'monthly_kurt': 'Monthly Kurt',
    'best_month': 'Best Month',
    'worst_month': 'Worst Month',
    'yearly_mean': 'Yearly Mean',
    'best_year': 'Best Year',
    'worst_year': 'Worst Year',
    'avg_drawdown': 'Avg. Drawdown',
    'avg_drawdown_days': 'Avg. Drawdown Days',
    'avg_up_month': 'Avg. Up Month',
    'avg_down_month': 'Avg. Down Month',
    'win_year_perc': 'Win Year %',
    'twelve_month_win_perc': 'Win 12m %'
}

# Apply renaming for readability
display_performance_stats.rename(index=rename_dict, inplace=True)

# Print or return the formatted DataFrame for display
display_performance_stats.loc[[
    'Start', 'End', 'Risk-free rate', 'Total Return', 'CAGR', 'Max Drawdown',
    'Calmar Ratio', 'MTD', '3m', '6m', 'YTD', 'Since Incep. (ann.)',
    'Best Day', 'Worst Day', 'Monthly Sharpe', 'Monthly Sortino',
    'Monthly Mean (ann.)', 'Monthly Vol (ann.)', 'Monthly Skew', 'Monthly Kurt',
    'Best Month', 'Worst Month','Avg. Drawdown', 'Avg. Drawdown Days',
    'Avg. Up Month', 'Avg. Down Month'
    ]]

"""**Automating the trading bot that automatically executes the Hierarchical Risk Parity (HRP) Strategy**

This section introduces a trading bot that automatically executes the Hierarchical Risk Parity strategy, converting targeted allocations into market orders while managing existing positions and respecting minimum trade thresholds. The bot also features a preview mode to validate trades before execution.

The preview_mode flag allows users to test the trading bot without executing real trades, providing a safeguard and a means to validate the bot's logic before live operation.

If preview_mode is set to False, then the trading bot will execute live orders. Use with caution.


The min_trade_value is set to $100, indicating that the bot will ignore any trades below this amount to ensure that transactions are economically viable.

**How it Works:**

It first initialize the trading bot, fetching current account details and holdings.
It assesses the portfolio's value, cash availability, and buying power.

Based on the optimized weights from our strategy, the bot prepares a list of trades, considering the minimum trade value threshold to avoid executing economically insignificant trades.

The trading bot then simulates the execution of these trades, providing an overview of buy and sell orders.

This simulation allows for a final review before live trading, ensuring alignment with our strategy and capital allocation rules.
"""

def create_positions_dataframe(account_positions):
    temp_df = pd.DataFrame(account_positions)
    columns = [temp_df.iloc[0, i][0] for i in range(len(temp_df.columns))]
    values = [[temp_df.iloc[j, i][1] for i in range(len(temp_df.columns))]
              for j in range(len(temp_df))]
    df_positions = pd.DataFrame(values, columns=columns)
    try:
        df_positions['symbol'] = df_positions['symbol'].apply(
            lambda x: x.split('USD')[0] + '/USD')
        df_positions.set_index('symbol', inplace=True)
        df_positions = df_positions.apply(
            lambda col: pd.to_numeric(col, errors='ignore'))
        return df_positions
    except KeyError:
        return pd.DataFrame(
            columns=['qty', 'side', 'market_value', 'cost_basis']
        )

preview_mode = False # If preview_mode is set to False, then the trading bot will
# execute live orders. Use with caution.
min_trade_value = 100  # Minimum dollar value per trade

print('Starting Trading Bot...\n')

# Get account details
account = trading_client.get_account()
account = pd.DataFrame(account, columns=['Field', 'Details']).set_index('Field')

# Get portfolio value
portfolio_value = float(account.loc['portfolio_value'].values[0])

# Get current account positions
account_positions = trading_client.get_all_positions()
account_positions = create_positions_dataframe(account_positions)

# Print account details and positions
print(f'Portfolio Value: {f"${portfolio_value:,.2f}"}')
print(f'Cash: ${float(account.loc["cash"].squeeze()):,.2f}')
print(f'Buying Power: ${float(account.loc["buying_power"].squeeze()):,.2f}\n')
if not account_positions.empty:
    print('Account Holdings: \n{}'.format(
        account_positions[['qty', 'side', 'market_value', 'cost_basis']]))
else:
    print('No positions in the portfolio.')

# Define lists to hold sell and buy trade instructions
sell_trades = []
buy_trades = []

# Function to prepare trades based on target and current values
def prepare_trade(symbol, target_value, current_value, current_qty,
                  current_price):
    difference = target_value - current_value
    if difference > 0:
        # Positive difference indicates a buy order
        notional = round(difference, 2)  # Calculate notional value to buy
        if notional >= min_trade_value:  # Skip small value trades
            buy_trades.append((symbol, notional, OrderSide.BUY))
    elif difference < 0:
        # Negative difference indicates a sell order
        notional = round(-difference, 2)  # Calculate notional value to sell
        if notional >= min_trade_value:  # Skip small value trades
            sell_trades.append((symbol, notional, OrderSide.SELL))

# Function to execute or preview trades
def execute_trade(symbol, notional, order_side, preview=True):
    trade_message = (f"{'Preview' if preview else 'Executed'} "
                     f"{order_side.value.lower()} order for "
                     f"{symbol}: Notional ${notional:,.2f}")
    if preview:
        trade_messages.append(trade_message)
    else:
        market_order_data = MarketOrderRequest(
            symbol=symbol,
            notional=notional,
            side=order_side,
            time_in_force=TimeInForce.GTC
        )
        try:
            trading_client.submit_order(order_data=market_order_data)
            trade_messages.append(trade_message)
        except Exception as e:
            trade_messages.append(f"Failed to execute "
                                  f"{order_side.value.lower()} order for "
                                  f"{symbol}: {e}")

print('\nPreparing Trades...\n')

# Collect trades based on current portfolio vs. target weights
for ticker, row in tqdm(weights.iterrows(), total=weights.shape[0]):
    symbol = ticker_mapping.get(ticker)
    if symbol is None:
        print(f"No mapping found for ticker {ticker}")
        continue

    target_weight = row['Optimized Weights']
    target_value = portfolio_value * target_weight

    if symbol in account_positions.index:
        position_row = account_positions.loc[symbol]
        current_value = position_row['market_value']
        current_qty = position_row['qty']
        current_price = current_prices.loc[symbol]
    else:
        current_value = 0
        current_qty = 0
        current_price = 0

    # Prepare trade without executing it immediately
    prepare_trade(symbol, target_value, current_value, current_qty,
                  current_price)

print('\n\nPreviewing Trades...\n' if preview_mode else \
      '\n\nExecuting Trades...\n')

trade_messages = []

for trade in sell_trades + buy_trades:
    execute_trade(*trade, preview=preview_mode)

for message in trade_messages:
    print(message)

print(f'\nTotal Trades: {len(sell_trades) + len(buy_trades)}'
      f'\nSell Trades: {len(sell_trades)}'
      f'\nBuy Trades: {len(buy_trades)}')

print('\nDone!')
